spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://admin-service-svc:8080
        instance:
          service-host-type: ip
  cloud:
    loadbalancer:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.selm.ag/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.selm.ag/realms/selmag
            user-info-authentication-method: bearer
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: manager-app
            client-secret: jAvbRzDmL130wxyxoOnhpYvPPTf5j0Vg
            scope:
              - openid
              - microprofile-jwt
          metrics:
            client-id: manager-app-metrics
            client-secret: N2afq4q9iAFvbUalBZwerVZOx8T5KQUR
            provider: keycloak
            authorization-grant-type: client_credentials
            scope:
              - metrics
eureka:
  client:
    serviceUrl:
      defaultZone: http://selmag-eureka-svc:8761/eureka/
    enabled: false
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo-svc:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
    enabled: true