spring:
  security:
    oauth2:
      client:
        registration:
          keycloak-login:
            client-id: admin-service
            client-secret: xPeqUPFVyY7p8lOOrEsUSjTnV0Un7YwF
            authorization-grant-type: authorization_code
            provider: keycloak
            scope:
              - openid
              - microprofile-jwt
          keycloak-client:
            client-id: admin-service
            client-secret: xPeqUPFVyY7p8lOOrEsUSjTnV0Un7YwF
            authorization-grant-type: client_credentials
            provider: keycloak
            scope:
              - metrics
