spring:
  datasource:
    url: jdbc:postgresql://catalogue-db-svc:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - catalogue
  boot:
    admin:
      client:
        enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.selm.ag/realms/selmag
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo-svc:9411/api/v2/spans
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://selmag-eureka-svc:8761/eureka/
keycloak:
  uri: https://auth.selm.ag
springdoc:
  swagger-ui:
    oauth:
      app-name: catalogue-swagger-ui
      client-id: catalogue-swagger-ui
      client-secret: O2gKU6kEAlNuxFjh16zPkREPIbe9IvVd
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true