spring:
  boot:
    admin:
      client:
        enabled: false
  cloud:
    gateway:
      routes:
        - id: catalogue-api-route
          uri: lb://catalogue-service
          predicates:
            - Host=catalogue.api.selm.ag
        - id: reviews-api-route
          uri: lb://reviews-service
          predicates:
            - Host=reviews.api.selm.ag
        - id: manager-app-route
          uri: lb://manager-app
          predicates:
            - Host=manager.selm.ag
        - id: customer-app-route
          uri: lb://customer-app
          predicates:
            - Host=customer.selm.ag
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.selm.ag/realms/selmag
      client:
        registration:
          keycloak:
            client-id: api-gateway
            client-secret: JAxjB4noMvVWA7vihqinqAJBaEQICwTf
            authorization-grant-type: client_credentials
            scope:
              - metrics
        provider:
          keycloak:
            issuer-uri: https://auth.selm.ag/realms/selmag
            user-name-attribute: preferred_username
server:
  forward-headers-strategy: native
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo-svc.default:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-svc.default:8761/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5