spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://selmag-admin-server-svc:8080
        instance:
          service-host-type: ip
  data:
    mongodb:
      uri: mongodb://reviews-db-svc:27017/reviews-db
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.selm.ag/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: reviews-service
            client-secret: UENa9wW8fiaOqFOEBe8CJiREBtkbIOMN
            authorization-grant-type: client_credentials
            scope:
              - metrics
      resourceserver:
        jwt:
          issuer-uri: https://auth.selm.ag/realms/selmag
management:
  metrics:
    mongo:
      command:
        enabled: false
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo-svc:9411/api/v2/spans
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://selmag-eureka-svc:8761/eureka/
keycloak:
  uri: https://auth.selm.ag
springdoc:
  swagger-ui:
    oauth:
      app-name: reviews-swagger-ui
      client-id: reviews-swagger-ui
      client-secret: clkSFrigY1zUbTU7u9aFm2b4bbDRqrTo
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true