spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://auth.selm.ag/realms/selmag
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://auth.selm.ag/realms/selmag
eureka:
  client:
    serviceUrl:
      defaultZone: http://${SELMAG_EUREKA_SVC_SERVICE_HOST}:${SELMAG_EUREKA_SVC_SERVICE_PORT}/eureka/
server:
  ssl:
    enabled: true
    trust-certificate: |
      -----BEGIN CERTIFICATE-----
      MIIDbzCCAlegAwIBAgIQTkoqIfHfO2FM48uxfBoAtDANBgkqhkiG9w0BAQsFADBL
      MRAwDgYDVQQKEwdBY21lIENvMTcwNQYDVQQDEy5LdWJlcm5ldGVzIEluZ3Jlc3Mg
      Q29udHJvbGxlciBGYWtlIENlcnRpZmljYXRlMB4XDTI0MDEyMzAyMjAxNVoXDTI1
      MDEyMjAyMjAxNVowSzEQMA4GA1UEChMHQWNtZSBDbzE3MDUGA1UEAxMuS3ViZXJu
      ZXRlcyBJbmdyZXNzIENvbnRyb2xsZXIgRmFrZSBDZXJ0aWZpY2F0ZTCCASIwDQYJ
      KoZIhvcNAQEBBQADggEPADCCAQoCggEBAJxkcx4jhvXxqIxCx6Lrk8jNjTYmLN1M
      zvvxPTN6wZKB2LF0EjjyXyAbBR0/mEtEva9ZE8kf3EW41B15rmIuSJp1CSTt/Jlt
      YN6/fT4pc37A4LsY/JrS5Mo6Kgxngys8pBYR4OK2nBo225elPx3x05em/9c/ZTPF
      WFkhVd4+pDn8hfN1Y+ZNrriQeiDcpzGJqIjU885E2qbSuoQatVEhokdex3/mPV8C
      ClXQiplfZxpz50J0FurmXwQc8I60EnMU2qJQG4DoaoPUaCSmDZgvdcf36lX1B6RC
      fkIvX0Nj5nvvtEgAGNhfGaUiPmkHF0dgHzt910MLW8MNq8v7u++0QoMCAwEAAaNP
      ME0wDgYDVR0PAQH/BAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMBMAwGA1UdEwEB
      /wQCMAAwGAYDVR0RBBEwD4INaW5ncmVzcy5sb2NhbDANBgkqhkiG9w0BAQsFAAOC
      AQEAQZLBQzOdfsTq4LCIVxNiiwlGgi03DbDZdQQ5CiV3RJV9wo17UfIPsPnVq969
      NvqY9xvTiKHTyswcSsQ/jtHK1ANQY0zG+mcEy/1XCN5FRsl2/sOhQ/o49HiFBihI
      9AZ6wcq35pz6ze5jIYYvvXw65pwOA/xLrbeBZo+b9RHBqXEFM0js4aiz4f6wpW2T
      oiNuoa+qDQiDy+63caPl9jjArVNWQjS0zzVSN8OLGZeDwi7TIL+Ad/5jxi3hUkKL
      slC5On672TCqtTY+4cVErNyf6H93FmJfNUICEGFdsRq+bU+klUL4e38xg9hNFKoL
      8VpGUUoVXZlGu+x9O1pdv3guCA==
      -----END CERTIFICATE-----