spring:
  boot:
    admin:
      client:
        enabled: true
        url: http://selmag-admin-server-svc:8080
        instance:
          service-host-type: ip
  datasource:
    url: jdbc:postgresql://catalogue-db-svc:5432/catalogue
    username: catalogue
    password: catalogue
  flyway:
    schemas:
      - catalogue
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: catalogue-service
            client-secret: 6SgV6OWCy6Pbb7frlfz6gRjbzjMvph6s
            authorization-grant-type: client_credentials
            scope:
              - metrics
        provider:
          keycloak:
            issuer-uri: https://auth.selm.ag/realms/selmag
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: https://auth.selm.ag/realms/selmag
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  info:
    env:
      enabled: true
  tracing:
    enabled: true
  zipkin:
    tracing:
      endpoint: http://tempo-svc:9411/api/v2/spans
eureka:
  instance:
    prefer-ip-address: true
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://selmag-eureka-svc:8761/eureka/
keycloak:
  uri: https://auth.selm.ag
springdoc:
  swagger-ui:
    oauth:
      app-name: catalogue-swagger-ui
      client-id: catalogue-swagger-ui
      client-secret: O2gKU6kEAlNuxFjh16zPkREPIbe9IvVd
      use-pkce-with-authorization-code-grant: true
      use-basic-authentication-with-access-code-grant: true